# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest
    container:
      image: rocker/geospatial:latest
    env:
      CACHE_CI: ${{ github.workspace }}/ci
      R_LIBS_USER: ${{ github.workspace }}/ci/lib
      NOT_CRAN: "true"
    steps:
      - uses: actions/checkout@v4
      - name: Set up cache
        run: |
          mkdir -p $R_LIBS_USER
          echo "R_LIBS='$R_LIBS_USER'" > .Renviron
      - name: Install remotes
        run: Rscript -e 'if (!require(remotes)) install.packages("remotes")'
      - name: Install dependencies
        run: Rscript -e 'remotes::install_deps(dependencies = TRUE)'
      - name: Update rcmdcheck
        run: Rscript -e 'remotes::update_packages("rcmdcheck")'
      - name: Run checks
        run: Rscript -e 'rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")'
    continue-on-error: true

  deploy:
    runs-on: ubuntu-latest
    container:
      image: rocker/geospatial:latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Set up cache
        run: |
          mkdir -p $R_LIBS_USER
          echo "R_LIBS='$R_LIBS_USER'" > .Renviron
      - name: Install dependencies
        run: Rscript -e 'devtools::install(dependencies = TRUE)'
      - name: Build site
        run: Rscript -e 'fairify::build_site()'
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: public
          path: public

  cache:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Docker image
        uses: actions/cache@v3
        with:
          path: /var/lib/docker
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-
